### ISSUE TITLE
Dropdown of projects

### ISSUE THREAD

**Issue by mathstuf** [svijee/taskwarrior-androidapp#15]
When adding a task, there should be a dropdown of existing projects.

**Comment by svijee** [comment]
AutoCompleteTextView seems to be the right thing for this instead of a regular dropdown.(http://developer.android.com/guide/topics/ui/controls/text.html#AutoComplete)

**Comment by mathstuf** [comment]
On the latest build, the dropdown list is just showing empty boxes, though the strings fill in properly. Galaxy Nexus with 4.1.x.

**Comment by svijee** [comment]
Yepp, there is an extra Issue #24 for this bug.
