### ISSUE TITLE
Task list tap actions feel inconsistent

### ISSUE THREAD

**Issue by mathstuf** [svijee/taskwarrior-androidapp#16]
A short tap should either edit or open a menu; select mode should be long click. This is how other applications with lists work at least.

**Comment by svijee** [comment]
I changed the way how to modify/delete/done tasks. Please have a look on it and discuss on the mailing list. Thanks! :)

**Comment by mathstuf** [comment]
On Sun, Mar 31, 2013 at 03:42:02 -0700, Sujeevan Vijayakumaran wrote:

> I changed the way how to modify/delete/done tasks. Please have a look
> on it and discuss on the mailing list. Thanks! :)

Thanks! Are there new builds available? My eclipse install didn't work
last I tried (yay Rawhide!).

--Ben

**Comment by svijee** [comment]
I've posted a current APK on the mailinglist (https://groups.google.com/forum/?fromgroups=#!topic/taskwarrior-android/IaufUAiyhXU).

**Comment by mathstuf** [comment]
On Sun, Mar 31, 2013 at 14:29:27 -0400, Ben Boeckel wrote:

> Are there new builds available?

Whoops, spoke too soon; I see them on the list now.

--Ben
