### ISSUE TITLE
add option to save tasks on internal storage

### ISSUE THREAD

**Issue by bugamn** [svijee/taskwarrior-androidapp#33]
When started, the program displays the displays the message "/mnt/sdcard/pending.data (Permission denied) Unable to read to external storage". I can't add then any tasks.

I'm testing on a Motorola XT860 (Milestone 3) without external SD card.

Edit: just discovered that my phone couldn't access the memory because it was connected to the pc. I would like to be able to access my tasks while I leave my phone connected to charge, but now I'm not sure how would that be possible.

**Comment by svijee** [comment]
You can access your tasks when your phone is charging. But you can't access your tasks when you have mounted your external storage on your pc.

But yes, there should be an option to save the taskdata in the internal storage.

**Comment by svijee** [comment]
Hmm, after a few hours, I think there's no good reason to implement this feature. The task datafiles are only unavaiable while the external storage is mounted on the pc, so it's avaiable the most of the time.

Closing this ticket for now.
