### ISSUE TITLE
edit screen needs contrasting headers

### ISSUE THREAD

**Issue by linuxcaffe** [svijee/taskwarrior-androidapp#35]
In the edit dialog, the field-headers and the field-contents are the same color and this is makes it less than clear what's what. I'd like to see the field-headers in an inverted scheme (white text on black or dark-gray bg) and the header font could be smaller.

**Comment by svijee** [comment]
Good point.

I don't agree with an inverted scheme. I think this one should be better:

http://developer.android.com/design/building-blocks/lists.html

The "Selection Divider" could be used for the field-headers (with or without a horizontal line)

**Comment by linuxcaffe** [comment]
sounds good, as long as it's clearly different from the content.
