### ISSUE TITLE
more data please!

### ISSUE THREAD

**Issue by linuxcaffe** [svijee/taskwarrior-androidapp#36]
This will obviously have to wait until the app supports more than the basic fields, but this is a suggestion for how the present display could be enhanced with more data, when available :)

![twdroid_mockup2](https://f.cloud.github.com/assets/2353531/544485/861a0f40-c250-11e2-8be9-e5f01e5d5b9b.png)

The attached mockup shows a truncated description and additional information; tags, task ID, blocked tasks, blocking tasks and number of annotations, and is a discussion-point.

**Comment by linuxcaffe** [comment]
to continue with the "visual feature requests", here's the latest mockup, now showing due and overdue condition and truncation in both states.

![twdroid_mockup4](https://f.cloud.github.com/assets/2353531/550001/f2341256-c305-11e2-9a1b-3d4a2d1543ea.png)

This also demonstrates some "time trimming" where, if the time is as default (ie. 12:00am) then it is presumed not to have been specified, so for clarity, it is not displayed. This makes the times you DID set stand out.

**Comment by linuxcaffe** [comment]
and here's an idea for making your lists a bit more compact, just as taskwarrior now has an option to drop a column if there are no values in the field, the app could have an option to skip empty rows. The only caveat I can think of is the ID, while always present, might not have to force the display of a line, as long as you could always see the ID with "options open".

![twdroid_mockup5](https://f.cloud.github.com/assets/2353531/550853/f6bf4a3c-c31b-11e2-950f-fa866f9ffbc0.png)

another feature-let shown here is a gray line indicating priority-not-specified, instead of white-on-white.

**Comment by linuxcaffe** [comment]
I drew a big doodle exploring the possible difference between reports; list, long, minimal. The ideas is that fields are presented in a consistent way, and each report can display different fields. 

![twdroid_listx3 4](https://f.cloud.github.com/assets/2353531/616432/bb29dee4-ce6d-11e2-8db9-61df08a0cbe3.png)

update: mockup now seriously linkified!
update: active tasks now show real-time accumulation, and are "sticky" at the top of list, long and minimal.
update: changed "next" references to "list"
update: used ubuntu color scheme

Notes:
- the <filter><report><count> list-header (pro:foo +baz due.before:eom long) doesn't correspond to the list-contents, in this case, but it should. 
- date-related data should always be grouped together and presented in date-order.
- The list report seeks to present a more consistent, three-line card, but will still skip blank lines.
- The long report could be called "the everything report" and seeks to expose all the data. This is like having all tasks in the "open" state (clicked and options visible) which could be considered our "info" view.
- The minimal report does it all with a single line per task.

**Comment by svijee** [comment]
Why did you close this issue? I will have a look on your ideas later.

**Comment by linuxcaffe** [comment]
must have been accidentally!, thanks for reopening, thanks for looking!
Take your time, and I'm not "precious" about any of it.

**Comment by linuxcaffe** [comment]
Here's a "kitchen sink" example, using all attributes, and an updated REPORT nav-tab

![twdroid_complete2](https://f.cloud.github.com/assets/2353531/620202/fe259c76-cede-11e2-8ab5-196088077827.png)

and yes, it's active! Click the star to issue the stop command.

**Comment by linuxcaffe** [comment]
Indentation + icon could be used to help indicate different task types; 
blocking, completed, deleted, waiting and active tasks.

![twdroid_types3](https://f.cloud.github.com/assets/2353531/597049/34932fce-cbd5-11e2-885c-05ee4a3e6d36.png)

update: darker green for pri:l, trimmed header off nav, trimmed attrib names to 3 chars, added waiting
update: active on top
update: experimenting with "ubuntu color scheme", you like it better? (I'm using this one as my color reference)

**Comment by linuxcaffe** [comment]
Using indentation, cross-references and (really bad) icons, a dependency-tree can be represented.

![twdroid_deps2](https://f.cloud.github.com/assets/2353531/616407/afb1c50a-ce6c-11e2-9e08-b646ae3335d6.png)

 or if your default report were "minimal", it might look like this;

![twdroid_mini-deps2](https://f.cloud.github.com/assets/2353531/616408/bc78a02e-ce6c-11e2-909b-a1678dd4748b.png)

updated colors

**Comment by linuxcaffe** [comment]
Regarding rotation, truncation and extended options;
when the device is in landscape mode, the list gets shorter and wider, obviously, allowing more details for fewer tasks, like "zooming in". One immediate benefit is being able to see (approx) twice as much before truncation, and the options bar now has double the real-estate. This is perhaps an opportunity for an extended option set, with things like annotate, duplicate, geo-locate and share.

![twdroid_wide-opts2](https://f.cloud.github.com/assets/2353531/618456/04174604-ceb5-11e2-990d-93eeb9bead65.png)

**Comment by svijee** [comment]
I'm closing this issue similar to issue #38. "More data" will be probably there, when you "click" on a task. Showing everything would too much work (and additionally too much for a phone).
