### ISSUE TITLE
display setting; padding

### ISSUE THREAD

**Issue by linuxcaffe** [svijee/taskwarrior-androidapp#37]
Some like their lists packed tight, some prefer breathing room, with a setting for padding, users could have it both ways. The default setting is something like 5px (?) and at 0px, tasks should be divided by a thin line, and the dropshadow can be turned off.

**Comment by svijee** [comment]
Hi,

personally I think, that there is no need for a setting. I think it's enough, when I (or someone else) minimizes the gap between the tasks. The current style is actually a bit too big which needs further improvements. So consequently the gap will be smaller for everyone and then, there wont be a need for a setting for a few pixels.

Is this okay for you?

**Comment by linuxcaffe** [comment]
works for me!
