### ISSUE TITLE
nav ideas

### ISSUE THREAD

**Issue by linuxcaffe** [svijee/taskwarrior-androidapp#38]
the NavDrawer needs some improvements, so I made another mockup. This time it's an animated .gif (8 seconds) to show three possible states for the nav..

![twdroid_nav-mockup3](https://f.cloud.github.com/assets/2353531/557254/cdb3f8d6-c3ed-11e2-86b1-7364864bbe3a.gif)

some notes;
FILTER
the filter can be entered manually in the box at the top, or, as items are selected, the filter-dialog is automatically filled-in. It should be possible to add a filter using the checkbox, and then edit that in the filter box. This can also act as a quick search-bar for "term" in description. 
Clicking the category headings should "accordion" the list. 
The gray checkmark on the filter-category indicates one-or-more selected from the category. 
Clicking the category checkbox cycles through three states; clear category, any-value-of-category, none-in-category (showing clear checkbox, green-checkmark and red-X, respectively)
Clicking on an attribute checkbox toggles inclusion in the filter list.
Clicking on an attribute name should make that a single selection, and go immediately to the active report.
Clicking on "apply" goes immediately to current report.
Missing; date parameters

SORT
Missing; UDAs

REPORT
Some of these will be easier, and some harder, but they are all important.
Missing; agenda, calendar

**Comment by svijee** [comment]
Can you post this gif as three seperate mockup picutures? It's a bit hard, if everything is jumping when I want to focus on a single screen.

Thank you!

**Comment by linuxcaffe** [comment]
![twdroid_nav-mockup_x3](https://f.cloud.github.com/assets/2353531/562537/729f051a-c4ad-11e2-9797-b9a00c6531b3.png)

**Comment by linuxcaffe** [comment]
and then more ideas. Don't worry, I think four main tabs will be all we need.. or could fit :)

![twdroid_nav-mockup8_x4](https://f.cloud.github.com/assets/2353531/581055/5ac355c2-c895-11e2-886b-605a71327c3a.png)

update: more sort options and minor clean-up.

**Comment by svijee** [comment]
I'm closing this issue. This feature request doesn't fit in my current plans for the app, because I want to keep it as simple as possible. (And there's no time to implement all these features.)
