### ISSUE TITLE
<filter> <report> <count> list-header

### ISSUE THREAD

**Issue by linuxcaffe** [svijee/taskwarrior-androidapp#39]
If you have a big list, the danger is that after filtering, you will miss something important. For that reason, it's essential that the user is always aware of the filters in play. One way of doing that is to display <filter> <report> at the top of each list. (see attached image) As a bonus, we can also show the report used and number matching tasks. 

![twdroid_top-mockup](https://f.cloud.github.com/assets/2353531/561215/c030806c-c488-11e2-8c99-e21b979693ee.png)

This form is designed to closely reproduce the command-line experience, so that the experienced taskwarrior user is right at home, and new users will become familiar with the cli filter syntax.

If the filter-set gets too big for a single line, it should "wrap" forcing as many new lines as needed. In order to help keep it condensed, there could be a user-setting where attribute-names (project: priority: etc) could be displayed using the .rc "minimum limit" (in my case, three characters, pro: pri: etc.)

**Comment by linuxcaffe** [comment]
Two other design elements, from the illustration above, are worth noting;

1) in the NavDrawer filter tab, notice the little numbers to the left of the checkboxes?

2) in the list mockup, I've tightened the color elements to eliminate the white spaces between bottom border, the priority-color and the due/overdue-color. This is primarily to smooth the effect, and reduce "visual turbulence" when scanning the list, but it also makes the box a teensy-bit shorter. With the gaps, it's like five "lines", including white, without the gap, it's more like two lines.

**Comment by svijee** [comment]
I've closed this issue regarding "<filter> <report> <count> list-header". I didn't implement anything regarding the navigation. This needs to be in another issue not in this one.

**Comment by svijee** [comment]
I have removed this feature currently, I've changed the type of navigation. It'll be avaiable soon again.

**Comment by svijee** [comment]
It's back!
