### ISSUE TITLE
App crashes on due notification

### ISSUE THREAD

**Issue by idolum** [svijee/taskwarrior-androidapp#42]
What I did:
- Added a task with today as due date
- Closed the app
- Starteded the app and when I get the due notification the app crashes (But not always, I do not get the notification then everything works fine (besides I get not notified about task I have to do today).

**Comment by svijee** [comment]
Should be fixed with commit https://github.com/svijee/taskwarrior-androidapp/commit/e0e616708d793da42b6282ed3fa50633a31c0c5d
