### ISSUE TITLE
multiple ~/.task databases, easily switchable

### ISSUE THREAD

**Issue by hessianerd** [svijee/taskwarrior-androidapp#44]
For those of us who have implemented http://taskwarrior.org/projects/taskwarrior/wiki/Faq4 

It would be great to be able to use multiple lists in the android app and make them easily switchable, or even merged and filterable.

**Comment by svijee** [comment]
> It would be great to be able to use multiple lists in the android app and make them easily switchable.

Yes, this sounds good.

> … or even merged and filterable.

Actually I don't see any advantages in merging and filtering two different task databases.

**Comment by svijee** [comment]
I've added a possibility to use more than one task database. This is currently a hidden feature. Now theres a subdirectoy "default"  where the default task database is located. If you create a new folder (with an external filemanager app), then you can switch between both databases in the apps settings.

**Comment by linuxcaffe** [comment]
I might be completely wrong here, but do the little red symbols that
follow taskwarrior-androidapp/res/values-de/strings.xml line #65 mean
"missing <CR>", or something?

**Comment by svijee** [comment]
Yes, but thats not a problem.

**Comment by linuxcaffe** [comment]
cool!
