### ISSUE TITLE
chose the location of the task data files

### ISSUE THREAD

**Issue by duckunix** [svijee/taskwarrior-androidapp#45]
I currently share my task files using owncloud (dropbox before that), and would love to be able to do that on the phone.

I know asking for direct integration would be a right pain, so how about the ability to set the location of the data files?

Thanks!

d

**Comment by svijee** [comment]
Actually there is no need for this feature. The final version will work with the upcoming task server. Therefore the app will switch to "normal" JSON which is not compatible with the task dataformat.
