### ISSUE TITLE
404 on Google Play

### ISSUE THREAD

**Issue by adaszko** [svijee/taskwarrior-androidapp#60]
Hello.  Just wanted to point out that I'm getting 404 for https://play.google.com/apps/testing/org.svij.taskwarriorapp

Is there any reason it is not on Google Play?  I would love to try it.

**Comment by ruworuro** [comment]
I think that you do not subcribe in google group.

In file README.md you can get the url to google group. Then you subscribe and you can download from google Play.

**Comment by svijee** [comment]
@ruworuro is right: Subscribe to this mailing list: https://groups.google.com/forum/#!forum/taskwarrior-android

Then you can open that link to Google Play. Final public release still needs some time.

**Comment by adaszko** [comment]
Works!  Thank you.
