### ISSUE TITLE
How to install and run on an Android device?

### ISSUE THREAD

**Issue by unfa** [svijee/taskwarrior-androidapp#62]
I've stumbled upon the project, read it's description, saw the screenshots.
Now I'd like to give it a go, but how? Are there any binary packages?
Or should I download the sources from GIT and build it myself?
If so - is there any instruction on how to accomplish that task?

**Comment by erikw** [comment]
I wrote instructions on how to build  in the README. Or download from Play store.

**Comment by svijee** [comment]
If you want to download it from the play store, you have to be subscribed to the Mailinglist (https://groups.google.com/forum/#!forum/taskwarrior-android), then visit this link: https://play.google.com/apps/testing/org.svij.taskwarriorapp

Then you can download it from the Play Store.
