### ISSUE TITLE
Syncing with taskd

### ISSUE THREAD

**Issue by hickey** [svijee/taskwarrior-androidapp#63]
Need documentation for how to connect taskwarrior with taskd. 

I am trying to connect with Freecinc. I have taken the key/cert/ca files and moved them in to the data directory and made entries in the config file. Uncertain if I am referring to the files correctly. Every time I try to sync, I get Taskserver credentials malformed.

**Comment by svijee** [comment]
You're in the wrong project. My project is abandoned. I guess you use [this](https://bitbucket.org/kvorobyev/taskwarriorandroid/wiki/Home) app.

**Comment by hickey** [comment]
Ah. Thank you for the correction.
